# Generated by Django 3.2 on 2023-05-09 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0003_auto_20230509_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
