# Generated by Django 3.2 on 2023-05-09 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0002_auto_20230509_0101'),
        ('reviews', '0004_remove_title_rating'),
    ]

    operations = []
