# Generated by Django 3.2 on 2023-05-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0005_merge_20230509_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(
                blank=True, null=True, verbose_name='Биография'
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                default='default@gmail.com', max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
