# Generated by Django 3.2 on 2023-05-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=models.Q(_negated=True, username__iexact='me'),
                name='username_is_not_me',
            ),
        ),
    ]
