# Generated by Django 3.2 on 2023-05-09 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0008_user_username_is_not_me'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='username_is_not_me',
        ),
    ]
