# Generated by Django 3.2 on 2023-05-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0010_auto_20230510_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('user', 'user'),
                    ('admin', 'admin'),
                    ('moderator', 'moderator'),
                ],
                default='user',
                max_length=50,
            ),
        ),
    ]
