# Generated by Django 3.2 on 2023-05-11 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                default='default@gmail.com',
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                max_length=150,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex='^[\\w.@+-]+\\z'
                    )
                ],
            ),
        ),
    ]
