# Generated by Django 3.2 on 2023-05-13 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0016_auto_20230513_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='titles',
                to='reviews.category',
                verbose_name='Категория',
            ),
        ),
    ]
