# Generated by Django 3.2 on 2023-05-15 17:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0017_alter_title_category'),
        ('reviews', '0017_auto_20230515_0012'),
    ]

    operations = []
